# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nexium/sp_vision_25

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nexium/sp_vision_25

# Include any dependencies generated for this target.
include tasks/omniperception/CMakeFiles/omniperception.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include tasks/omniperception/CMakeFiles/omniperception.dir/compiler_depend.make

# Include the progress variables for this target.
include tasks/omniperception/CMakeFiles/omniperception.dir/progress.make

# Include the compile flags for this target's objects.
include tasks/omniperception/CMakeFiles/omniperception.dir/flags.make

tasks/omniperception/CMakeFiles/omniperception.dir/decider.cpp.o: tasks/omniperception/CMakeFiles/omniperception.dir/flags.make
tasks/omniperception/CMakeFiles/omniperception.dir/decider.cpp.o: tasks/omniperception/decider.cpp
tasks/omniperception/CMakeFiles/omniperception.dir/decider.cpp.o: tasks/omniperception/CMakeFiles/omniperception.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/nexium/sp_vision_25/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object tasks/omniperception/CMakeFiles/omniperception.dir/decider.cpp.o"
	cd /home/nexium/sp_vision_25/tasks/omniperception && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT tasks/omniperception/CMakeFiles/omniperception.dir/decider.cpp.o -MF CMakeFiles/omniperception.dir/decider.cpp.o.d -o CMakeFiles/omniperception.dir/decider.cpp.o -c /home/nexium/sp_vision_25/tasks/omniperception/decider.cpp

tasks/omniperception/CMakeFiles/omniperception.dir/decider.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/omniperception.dir/decider.cpp.i"
	cd /home/nexium/sp_vision_25/tasks/omniperception && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/nexium/sp_vision_25/tasks/omniperception/decider.cpp > CMakeFiles/omniperception.dir/decider.cpp.i

tasks/omniperception/CMakeFiles/omniperception.dir/decider.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/omniperception.dir/decider.cpp.s"
	cd /home/nexium/sp_vision_25/tasks/omniperception && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/nexium/sp_vision_25/tasks/omniperception/decider.cpp -o CMakeFiles/omniperception.dir/decider.cpp.s

tasks/omniperception/CMakeFiles/omniperception.dir/perceptron.cpp.o: tasks/omniperception/CMakeFiles/omniperception.dir/flags.make
tasks/omniperception/CMakeFiles/omniperception.dir/perceptron.cpp.o: tasks/omniperception/perceptron.cpp
tasks/omniperception/CMakeFiles/omniperception.dir/perceptron.cpp.o: tasks/omniperception/CMakeFiles/omniperception.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/nexium/sp_vision_25/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object tasks/omniperception/CMakeFiles/omniperception.dir/perceptron.cpp.o"
	cd /home/nexium/sp_vision_25/tasks/omniperception && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT tasks/omniperception/CMakeFiles/omniperception.dir/perceptron.cpp.o -MF CMakeFiles/omniperception.dir/perceptron.cpp.o.d -o CMakeFiles/omniperception.dir/perceptron.cpp.o -c /home/nexium/sp_vision_25/tasks/omniperception/perceptron.cpp

tasks/omniperception/CMakeFiles/omniperception.dir/perceptron.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/omniperception.dir/perceptron.cpp.i"
	cd /home/nexium/sp_vision_25/tasks/omniperception && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/nexium/sp_vision_25/tasks/omniperception/perceptron.cpp > CMakeFiles/omniperception.dir/perceptron.cpp.i

tasks/omniperception/CMakeFiles/omniperception.dir/perceptron.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/omniperception.dir/perceptron.cpp.s"
	cd /home/nexium/sp_vision_25/tasks/omniperception && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/nexium/sp_vision_25/tasks/omniperception/perceptron.cpp -o CMakeFiles/omniperception.dir/perceptron.cpp.s

omniperception: tasks/omniperception/CMakeFiles/omniperception.dir/decider.cpp.o
omniperception: tasks/omniperception/CMakeFiles/omniperception.dir/perceptron.cpp.o
omniperception: tasks/omniperception/CMakeFiles/omniperception.dir/build.make
.PHONY : omniperception

# Rule to build all files generated by this target.
tasks/omniperception/CMakeFiles/omniperception.dir/build: omniperception
.PHONY : tasks/omniperception/CMakeFiles/omniperception.dir/build

tasks/omniperception/CMakeFiles/omniperception.dir/clean:
	cd /home/nexium/sp_vision_25/tasks/omniperception && $(CMAKE_COMMAND) -P CMakeFiles/omniperception.dir/cmake_clean.cmake
.PHONY : tasks/omniperception/CMakeFiles/omniperception.dir/clean

tasks/omniperception/CMakeFiles/omniperception.dir/depend:
	cd /home/nexium/sp_vision_25 && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/nexium/sp_vision_25 /home/nexium/sp_vision_25/tasks/omniperception /home/nexium/sp_vision_25 /home/nexium/sp_vision_25/tasks/omniperception /home/nexium/sp_vision_25/tasks/omniperception/CMakeFiles/omniperception.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : tasks/omniperception/CMakeFiles/omniperception.dir/depend

